import type { Metadata } from "next";
import Link from "next/link";
import axios from "axios";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  axios.interceptors.request.use((config) => {
    // config.headers["Authorization"] = `Bearer ${session?.accessToken}`;
    config.baseURL = "http://localhost:8000/api";
    return config;
  });

  axios.interceptors.response.use(
    (response) => {
      return response;
    },
    (error) => {
      if (error.response?.status === 401) {
      }
      return Promise.reject(error);
    }
  );
  return (
    <html lang="tr">
      <body className="bg-[url(/mock-images/login-bg.png)] bg-cover bg-center h-[100vh] flex items-center justify-center">
        <div className="absolute top-10 right-10 p-5 flex items-center justify-center  bg-black bg-opacity-50">
          <Link href="/" className="text-white text-2xl font-bold ml-5">
            Anasayfaya Dön
          </Link>
        </div>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
